#!/usr/bin/perl
#
# Count "txt" references per process in lsof output

$pc = $tl = $tpp = 0;
$pcmd = "undefined";
$ppid = -1;
while (<>) {
    @F = split(' ', $_, 999);
    if ($#F < 2) {
	$ct = $#F + 1;
	print STDERR "less than 2 fields ($ct): \"$\_\"\n";
	next;
    }
    $cmd = $F[0];
    if ($cmd eq "COMMAND") { next; }
    $pid = $F[1] + 0;
    $tl++;
    if ($ppid >= 0) {
	if ($pid == $ppid) { $tpp++; }
	else {
	    printf "%6d %4d %s\n", $ppid, $tpp, $pcmd;
	    $tpp = 0;
	}
    }
    if (!$tpp) {
	$pcmd = $cmd;
	$ppid = $pid;
	$pc++;
	$tpp = 1;
    }
}
if ($tpp) {
    printf "%6d %4d %s\n", $ppid, $tpp, $pcmd;
}
printf "PIDs = %d, txt = %d, txt/PID = %f\n", $pc, $tl, $tl/$pc;
exit(0);
