#!/bin/ksh
#
# LinuxDistrib -- make Linux distribution of lsof 4.x
#
# Usage: LinuxDistrib [<suffix>]
#
#	 <suffix>	optional suffix for identification

if test $# -gt 1
then
  echo "Usage: [<suffix>]"
  exit 1
fi

if ! test -d support; then
  echo "run this script at the top directory of source tree"
  exit 1
fi

$(dirname $0)/GenericDistrib2 linux $1
