#!/bin/ksh
#
# NetBSDDistrib -- make NetBSD distribution of lsof 4.x
#
# Usage: NetBSDDistrib [<suffix>]
#
#	 <suffix>	optional suffix for identification

if test $# -gt 1
then
  echo "Usage: [<suffix>]"
  exit 1
fi
$HOME/src/lsof4/support/GenericDistrib2 netbsd $1
