freebsd13_task:
  freebsd_instance:
    image: freebsd-13-0-current-amd64-v20190531
  timeout_in: 120m
  install_script: pkg install -y git bash
  script:
    - ./Configure -n freebsd
    - make
    - bash ./check.bash freebsd

freebsd12_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  timeout_in: 120m
  install_script: pkg install -y git bash
  script:
    - ./Configure -n freebsd
    - make
    - bash ./check.bash freebsd

freebsd11_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64
  timeout_in: 120m
  install_script: pkg install -y git bash
  script:
    - ./Configure -n freebsd
    - make
    - bash ./check.bash freebsd
