task:
  freebsd_instance:
    cpu: 1
    matrix:
      - image: freebsd-13-0-release-amd64
      - image: freebsd-12-2-release-amd64
      - image: freebsd-11-4-release-amd64
  install_script: pkg install -y bash
  build_script:
    - ./Configure -n freebsd
    - make
  test_script:
    - bash ./check.bash freebsd
