#!/bin/ksh
#
# GenericRdist -- generically rdist lsof 4.x sources to a specified destination
#
# Usage: GenericRdist <destination> <dialect> <shell>
#
#	 <destination>	destination host
#
#	 <dialect>	dialect subdirectory name
#
#	 <shell>	remote shell -- rsh or ssh

# Process arguments.

if test $# -ne 3
then
  echo "Usage: <destination> <dialect> <shell>"
  exit
fi
H=$1
D=$2
S=$3

# Test the shell and define it's full path, as required.

if test "X$S" = "Xrsh"
then
  SHP=""
else
  if test "X$S" = "Xssh"
  then
    SHP="-P /opt/openssh/bin/ssh"
  else
    echo "$S is not an acceptable shell; specify rsh or ssh."
    exit
  fi
fi

# Define the distfile and make sure it's removed on premature exit.

R=/tmp/distfile.$$
trap 'rm $R; exit 1' 1 2 3 15

rm -f $R
echo ". -> $H" > $R
echo "	except ( ./00.README.FIRST ./00DCACHE ./00DIST ./00FAQ );" >> $R
echo "	except ( ./00PORTING ./00README ./00CREDITS ./00QUICKSTART );" >> $R
echo "	except ( ./00LSOF-L ./00MANIFEST ./00XCONFIG ./.ck00MAN );" >> $R
echo "	except ( ./00TEST ./.neverCust ./.neverInv );" >> $R
echo "	except ( ./Makefile ./arg.o ./main.o ./misc.o ./node.o );" >> $R
echo "	except ( ./print.o ./proc.o ./store.o ./usage.o );" >> $R
echo "	except ( ./lsof ./lsof32 ./lsof64 ./lsof_old /lsof_32.old );" >> $R
echo "	except ( ./lsof_64.old ./Lsof.8 );" >> $R
echo "	except ( ./ddev.c ./dfile.c ./dlsof.h ./dmnt.c ./dnode.c );" >> $R
echo "	except ( ./dnode1.c ./dnode2.c ./dproc.c ./dproto.h );" >> $R
echo "	except ( ./dsock.c ./dstore.c );" >> $R
echo "	except ( ./ddev.o ./dfile.o ./dmnt.o ./dnode.o ./dnode1.o );" >> $R
echo "	except ( ./dnode2.o ./dproc.o ./dsock.o ./dstore.o );" >> $R
echo "	except ( ./arg.o ./main.o ./misc.o ./node.o ./print.o ./proc.o );" >> $R
echo "	except ( ./store.o ./usage.o );" >> $R
echo "	except ( ./kernelbase.h ./machine.h ./version.h ./zipme );" >> $R
echo "	except ( ./NEW ./OLD ./RCS ./dialects ./support ) ;" >> $R
echo "	except ( ./make.out ./new ./old ./out ./X ./xxx ./errs ) ;" >> $R
echo "	except ( ./lib/Makefile ./lib/RCS ./lib/OLD ./lib/NEW );" >> $R
echo "	except ( ./lib/ckkv.o ./lib/cvfs.o ./lib/dvch.o ./lib/fino.o );" >> $R
echo "	except ( ./lib/isfn.o ./lib/lkud.o ./lib/pdvn.o ./lib/prfp.o );" >> $R
echo "	except ( ./lib/ptti.o ./lib/rdev.o ./lib/regex.o ./lib/rmnt.o );" >> $R
echo "	except ( ./lib/rnam.o ./lib/rnch.o ./lib/rnmh.o ./lib/snpf.o );" >> $R
echo "	except ( ./lib/liblsof.a );" >> $R
echo "	except ( ./scripts/OLD ./scripts/NEW ./scripts/RCS ) ;" >> $R
echo "	except ( ./scripts/00MANIFEST ./scripts/00README ) ;" >> $R
echo "	except ( ./tests/OLD ./tests/NEW ./tests/RCS ) ;" >> $R
echo "	except ( ./tests/00README ) ;" >> $R
echo "	except ( ./tests/LTbasic ./tests/LTbigf ./tests/LTdnlc ) ;" >> $R
echo "	except ( ./tests/LTlock ./tests/LTnfs ./tests/LTnlink ) ;" >> $R
echo "	except ( ./tests/LTsock ./tests/LTszoff ./tests/LTunix ) ;" >> $R
echo "	except ( ./tests/LTbasic.o ./tests/LTbigf.o ./tests/LTdnlc.o ) ;" >> $R
echo "	except ( ./tests/LTlib.o ./tests/LTlock.o ./tests/LTnfs.o );" >> $R
echo "	except ( ./tests/LTnlink.o ./tests/LTsock.o ./tests/LTszoff.o );" >> $R
echo "	except ( ./tests/LTunix.o ) ;" >> $R
echo "	except ( ./tests/config.cc ./tests/config.cflags ) ;" >> $R
echo "	except ( ./tests/config.ldflags ./tests/config.xobj ) ;" >> $R
echo "	install src/lsof4 ;" >> $R
echo "" >> $R
echo "./dialects/$D -> $H" >> $R
echo "	except ( ./dialects/$D/NEW );" >> $R
echo "	except ( ./dialects/$D/OLD ./dialects/$D/RCS );" >> $R
echo "	install src/lsof4/dialects/$D ;" >> $R

# Do the actual distribution.

(cd $HOME/src/lsof4; /usr/local/bin/rdist $SHP -f $R)
#DEBUGrm $R
echo done
