#!/bin/sh
#
# lsofbin <version> -- update lsof_<version> binary and associated info, using
#		       gzip
#
# lsof2bin <version> -- update lsof_<version> binary and associated info, using
#		        bzip2

if test $# -ne 1
then
  echo "Usage: lsofbin <version>"
  exit 1
fi
echo $0 | grep 2 > /dev/null
if test $? -eq 0
then
  C=bzip2
  S=bz2
else
  C=gzip
  S=gz
fi

if test ! -r lsof_$1
then
  echo lsof_$1 not found
  exit 1
fi

rm -f CHECKSUMS lsof_${1}.sig
chmod 755 lsof_$1

$C lsof_$1
echo $PGPPASS | gpg -o lsof_${1}.sig --passphrase-fd 0 -b lsof_${1}.$S
chmod 644 *.sig

echo "" > CHECKSUMS
md5 lsof_${1}.$S | sed 's/MD5 /	MD5:	/' >> CHECKSUMS
echo "	sum:	\c" >> CHECKSUMS
sum -r lsof_${1}.$S  >> CHECKSUMS
cat >> CHECKSUMS << ENDTEXT

You may need to use sum's -r option (or cksum -o1) to get a matching
result.  Even then the block count may not match, depending on the
block size your sum (or cksum) program reports.  The sum program
that generated the above value considers block size to be 512.

The most reliable authentication method is to use GPG with the detached
certificate in lsof_${1}.sig -- e.g.,

        \$ gpg --verify lsof_${1}.sig lsof_${1}.$S

Victor A. Abell
ENDTEXT

date >> CHECKSUMS
ls -l
cat CHECKSUMS
