#!/bin/sh
#
# Compare lsof sources

A=$HOME/src/lsof-Apple
S=$HOME/src/lsof4

cd $S
echo "==== $S ===="
for i in Configure
do
  echo "*** $i ***"
  if test -r $A/$i
  then
    diff -c $A/$i $i
  else
    echo "!!!! $i doesn't exist in $A !!!!"
  fi
done
