#!/bin/sh
#
# Compare lsof Darwin libproc sources

A=$HOME/src/lsof-Apple/dialects/kmem/libproc
S=$HOME/src/lsof4/dialects/kmem/libproc

cd $S
echo "==== $S ===="
for i in *.[ch] Makefile Mksrc
do
  echo "*** $i ***"
  if test -r $A/$i
  then
    diff -c $A/$i $i
  else
    echo "!!!! $i doesn't exist in $A !!!!"
  fi
done
