#!/bin/sh
#
# Compare lsof sources

A=$HOME/src/lsof-Apple/scripts
S=$HOME/src/lsof4/scripts

cd $S
echo "==== $S ===="
for i in *.perl *.perl5 *.awk 00README 00MANIFEST
do
  echo "*** $i ***"
  if test -r $A/$i
  then
    diff -c $A/$i $i
  else
    echo "!!!! $i doesn't exist in $A !!!!"
  fi
done
