#!/bin/sh
#
# Compare lsof sources

A=$HOME/src/lsof-Apple/tests
S=$HOME/src/lsof4/tests

cd $S
echo "==== $S ===="
for i in *.[ch] Makefile Add2TestDB CkTestDB TestDB
do
  echo "*** $i ***"
  if test -r $A/$i
  then
    diff -c $A/$i $i
  else
    echo "!!!! $i doesn't exist in $A !!!!"
  fi
done
