enum lsof_protocol {
    /* Follow ip protocol numbers order */
    LSOF_PROTOCOL_IP,           /**< IP(0) */
    LSOF_PROTOCOL_HOPOPTS,      /**< HOPOPTS(0) */
    LSOF_PROTOCOL_ICMP,         /**< ICMP(1) */
    LSOF_PROTOCOL_IGMP,         /**< IGMP(2) */
    LSOF_PROTOCOL_GGP,          /**< GGP(3) */
    LSOF_PROTOCOL_IPIP,         /**< IPIP(4) */
    LSOF_PROTOCOL_IPV4,         /**< IPV4(4) */
    LSOF_PROTOCOL_TCP,          /**< TCP(6) */
    LSOF_PROTOCOL_ST,           /**< ST(7) */
    LSOF_PROTOCOL_EGP,          /**< EGP(8) */
    LSOF_PROTOCOL_PIGP,         /**< PIGP(9) */
    LSOF_PROTOCOL_RCCMON,       /**< RCCMON(10) */
    LSOF_PROTOCOL_NVPII,        /**< NVPII(11) */
    LSOF_PROTOCOL_PUP,          /**< PUP(12) */
    LSOF_PROTOCOL_ARGUS,        /**< ARGUS(13) */
    LSOF_PROTOCOL_EMCON,        /**< EMCON(14) */
    LSOF_PROTOCOL_XNET,         /**< XNET(15) */
    LSOF_PROTOCOL_CHAOS,        /**< CHAOS(16) */
    LSOF_PROTOCOL_UDP,          /**< UDP(17) */
    LSOF_PROTOCOL_MUX,          /**< MUX(18) */
    LSOF_PROTOCOL_MEAS,         /**< MEAS(19) */
    LSOF_PROTOCOL_HMP,          /**< HMP(20) */
    LSOF_PROTOCOL_PRM,          /**< PRM(21) */
    LSOF_PROTOCOL_IDP,          /**< IDP(22) */
    LSOF_PROTOCOL_TRUNK1,       /**< TRUNK1(23) */
    LSOF_PROTOCOL_TRUNK2,       /**< TRUNK2(24) */
    LSOF_PROTOCOL_LEAF1,        /**< LEAF1(25) */
    LSOF_PROTOCOL_LEAF2,        /**< LEAF2(26) */
    LSOF_PROTOCOL_RDP,          /**< RDP(27) */
    LSOF_PROTOCOL_IRTP,         /**< IRTP(28) */
    LSOF_PROTOCOL_TP,           /**< TP(29) */
    LSOF_PROTOCOL_BLT,          /**< BLT(30) */
    LSOF_PROTOCOL_NSP,          /**< NSP(31) */
    LSOF_PROTOCOL_INP,          /**< INP(32) */
    LSOF_PROTOCOL_DCCP,         /**< DCCP(33) */
    LSOF_PROTOCOL_3PC,          /**< 3PC(34) */
    LSOF_PROTOCOL_IDPR,         /**< IDPR(35) */
    LSOF_PROTOCOL_XTP,          /**< XTP(36) */
    LSOF_PROTOCOL_DDP,          /**< DDP(37) */
    LSOF_PROTOCOL_CMTP,         /**< CMTP(38) */
    LSOF_PROTOCOL_TPXX,         /**< TPXX(39) */
    LSOF_PROTOCOL_IL,           /**< IL(40) */
    LSOF_PROTOCOL_IPV6,         /**< IPV6(41) */
    LSOF_PROTOCOL_SDRP,         /**< SDRP(42) */
    LSOF_PROTOCOL_ROUTING,      /**< ROUTING(43) */
    LSOF_PROTOCOL_FRAGMENT,     /**< FRAGMENT(44) */
    LSOF_PROTOCOL_IDRP,         /**< IDRP(45) */
    LSOF_PROTOCOL_RSVP,         /**< RSVP(46) */
    LSOF_PROTOCOL_GRE,          /**< GRE(47) */
    LSOF_PROTOCOL_MHRP,         /**< MHRP(48) */
    LSOF_PROTOCOL_BHA,          /**< BHA(49) */
    LSOF_PROTOCOL_ESP,          /**< ESP(50) */
    LSOF_PROTOCOL_AH,           /**< AH(51) */
    LSOF_PROTOCOL_INLSP,        /**< INLSP(52) */
    LSOF_PROTOCOL_SWIPE,        /**< SWIPE(53) */
    LSOF_PROTOCOL_NHRP,         /**< NHRP(54) */
    LSOF_PROTOCOL_MOBILE,       /**< MOBILE(55) */
    LSOF_PROTOCOL_TLSP,         /**< TLSP(56) */
    LSOF_PROTOCOL_SKIP,         /**< SKIP(57) */
    LSOF_PROTOCOL_ICMPV6,       /**< ICMPV6(58) */
    LSOF_PROTOCOL_NONE,         /**< NONE(59) */
    LSOF_PROTOCOL_DSTOPTS,      /**< DSTOPTS(60) */
    LSOF_PROTOCOL_AHIP,         /**< AHIP(61) */
    LSOF_PROTOCOL_CFTP,         /**< CFTP(62) */
    LSOF_PROTOCOL_HELLO,        /**< HELLO(63) */
    LSOF_PROTOCOL_SATEXPAK,     /**< SATEXPAK(64) */
    LSOF_PROTOCOL_KRYPTOLAN,    /**< KRYPTOLAN(65) */
    LSOF_PROTOCOL_RVD,          /**< RVD(66) */
    LSOF_PROTOCOL_IPPC,         /**< IPPC(67) */
    LSOF_PROTOCOL_ADFS,         /**< ADFS(68) */
    LSOF_PROTOCOL_SATMON,       /**< SATMON(69) */
    LSOF_PROTOCOL_VISA,         /**< VISA(70) */
    LSOF_PROTOCOL_IPCV,         /**< IPCV(71) */
    LSOF_PROTOCOL_CPNX,         /**< CPNX(72) */
    LSOF_PROTOCOL_CPHB,         /**< CPHB(73) */
    LSOF_PROTOCOL_WSN,          /**< WSN(74) */
    LSOF_PROTOCOL_PVP,          /**< PVP(75) */
    LSOF_PROTOCOL_BRSATMON,     /**< BRSATMON(76) */
    LSOF_PROTOCOL_ND,           /**< ND(77) */
    LSOF_PROTOCOL_WBMON,        /**< WBMON(78) */
    LSOF_PROTOCOL_WBEXPAK,      /**< WBEXPAK(79) */
    LSOF_PROTOCOL_EON,          /**< EON(80) */
    LSOF_PROTOCOL_VMTP,         /**< VMTP(81) */
    LSOF_PROTOCOL_SVMTP,        /**< SVMTP(82) */
    LSOF_PROTOCOL_VINES,        /**< VINES(83) */
    LSOF_PROTOCOL_TTP,          /**< TTP(84) */
    LSOF_PROTOCOL_IGP,          /**< IGP(85) */
    LSOF_PROTOCOL_DGP,          /**< DGP(86) */
    LSOF_PROTOCOL_TCF,          /**< TCF(87) */
    LSOF_PROTOCOL_IGRP,         /**< IGRP(88) */
    LSOF_PROTOCOL_OSPFIGP,      /**< OSPFIGP(89) */
    LSOF_PROTOCOL_SRPC,         /**< SRPC(90) */
    LSOF_PROTOCOL_LARP,         /**< LARP(91) */
    LSOF_PROTOCOL_MTP,          /**< MTP(92) */
    LSOF_PROTOCOL_AX25,         /**< AX25(93) */
    LSOF_PROTOCOL_BEETPH,       /**< BEETPH(94) */
    LSOF_PROTOCOL_IPEIP,        /**< IPEIP(94) */
    LSOF_PROTOCOL_MICP,         /**< MICP(95) */
    LSOF_PROTOCOL_SCCSP,        /**< SCCSP(96) */
    LSOF_PROTOCOL_ETHERIP,      /**< ETHERIP(97) */
    LSOF_PROTOCOL_ENCAP,        /**< ENCAP(98) */
    LSOF_PROTOCOL_APES,         /**< APES(99) */
    LSOF_PROTOCOL_GMTP,         /**< GMTP(100) */
    LSOF_PROTOCOL_PIM,          /**< PIM(103) */
    LSOF_PROTOCOL_COMP,         /**< COMP(108) */
    LSOF_PROTOCOL_IPCOMP,       /**< IPCOMP(108) */
    LSOF_PROTOCOL_CARP,         /**< CARP(112) */
    LSOF_PROTOCOL_PGM,          /**< PGM(113) */
    LSOF_PROTOCOL_SCTP,         /**< SCTP(132) */
    LSOF_PROTOCOL_MH,           /**< MH(135) */
    LSOF_PROTOCOL_UDPLITE,      /**< UDPLITE(136) */
    LSOF_PROTOCOL_MPLS,         /**< MPLS(137) */
    LSOF_PROTOCOL_HIP,          /**< HIP(139) */
    LSOF_PROTOCOL_SHIM6,        /**< SHIM6(140) */
    LSOF_PROTOCOL_ETHERNET,     /**< ETHERNET(143) */
    LSOF_PROTOCOL_PFSYNC,       /**< PFSYNC(240) */
    LSOF_PROTOCOL_RESERVED_253, /**< RESERVED_253(253) */
    LSOF_PROTOCOL_RESERVED_254, /**< RESERVED_254(254) */
    LSOF_PROTOCOL_OLD_DIVERT,   /**< OLD_DIVERT(254) */
    LSOF_PROTOCOL_RAW,          /**< RAW(255) */
    LSOF_PROTOCOL_MAX,          /**< MAX(256) */
    LSOF_PROTOCOL_DONE,         /**< DONE(257) */
    LSOF_PROTOCOL_DIVERT,       /**< DIVERT(258) */
    LSOF_PROTOCOL_SEND,         /**< SEND(259) */
    LSOF_PROTOCOL_MPTCP,        /**< MPTCP(262) */
    LSOF_PROTOCOL_SPACER,       /**< SPACER(32767) */
    /* Follow ethernet type order */
    LSOF_PROTOCOL_802_3,      /**< 802_3(0x0001) */
    LSOF_PROTOCOL_ALL,        /**< ALL(0x0003) */
    LSOF_PROTOCOL_802_2,      /**< 802_2(0x0004) */
    LSOF_PROTOCOL_SNAP,       /**< SNAP(0x0005) */
    LSOF_PROTOCOL_DDCMP,      /**< DDCMP(0x0006) */
    LSOF_PROTOCOL_WAN_PPP,    /**< WAN_PPP(0x0007) */
    LSOF_PROTOCOL_PPP_MP,     /**< PPP_MP(0x0008) */
    LSOF_PROTOCOL_LOCALTALK,  /**< LOCALTALK(0x0009) */
    LSOF_PROTOCOL_CAN,        /**< CAN(0x000C) */
    LSOF_PROTOCOL_CANFD,      /**< CANFD(0x000D) */
    LSOF_PROTOCOL_CANXL,      /**< CANXL(0x000E) */
    LSOF_PROTOCOL_PPPTALK,    /**< PPPTALK(0x0010) */
    LSOF_PROTOCOL_TR_802_2,   /**< TR_802_2(0x0011) */
    LSOF_PROTOCOL_MOBITEX,    /**< MOBITEX(0x0015) */
    LSOF_PROTOCOL_CONTROL,    /**< CONTROL(0x0016) */
    LSOF_PROTOCOL_IRDA,       /**< IRDA(0x0017) */
    LSOF_PROTOCOL_ECONET,     /**< ECONET(0x0018) */
    LSOF_PROTOCOL_HDLC,       /**< HDLC(0x0019) */
    LSOF_PROTOCOL_ARCNET,     /**< ARCNET(0x001A) */
    LSOF_PROTOCOL_DSA,        /**< DSA(0x001B) */
    LSOF_PROTOCOL_TRAILER,    /**< TRAILER(0x001C) */
    LSOF_PROTOCOL_LOOP,       /**< LOOP(0x0060) */
    LSOF_PROTOCOL_PHONET,     /**< PHONET(0x00F5) */
    LSOF_PROTOCOL_IEEE802154, /**< IEEE802154(0x00F6) */
    LSOF_PROTOCOL_CAIF,       /**< CAIF(0x00F7) */
    LSOF_PROTOCOL_XDSA,       /**< XDSA(0x00F8) */
    LSOF_PROTOCOL_MAP,        /**< MAP(0x00F9) */
    LSOF_PROTOCOL_MCTP,       /**< MCTP(0x00FA) */
    LSOF_PROTOCOL_PUPAT,      /**< PUPAT(0x0201) */
    LSOF_PROTOCOL_802_3_MIN,  /**< 802_3_MIN(0x0600) */
    LSOF_PROTOCOL_X25,        /**< X25(0x0805) */
    LSOF_PROTOCOL_ARP,        /**< ARP(0x0806) */
    LSOF_PROTOCOL_BPQ,        /**< BPQ(0x08FF) */
    LSOF_PROTOCOL_IEEEPUP,    /**< IEEEPUP(0x0A00) */
    LSOF_PROTOCOL_IEEEPUPAT,  /**< IEEEPUPAT(0x0A01) */
    LSOF_PROTOCOL_ERSPAN2,    /**< ERSPAN2(0x22EB) */
    LSOF_PROTOCOL_TSN,        /**< TSN(0x22F0) */
    LSOF_PROTOCOL_BATMAN,     /**< BATMAN(0x4305) */
    LSOF_PROTOCOL_DEC,        /**< DEC(0x6000) */
    LSOF_PROTOCOL_DNA_DL,     /**< DNA_DL(0x6001) */
    LSOF_PROTOCOL_DNA_RC,     /**< DNA_RC(0x6002) */
    LSOF_PROTOCOL_DNA_RT,     /**< DNA_RT(0x6003) */
    LSOF_PROTOCOL_LAT,        /**< LAT(0x6004) */
    LSOF_PROTOCOL_DIAG,       /**< DIAG(0x6005) */
    LSOF_PROTOCOL_CUST,       /**< CUST(0x6006) */
    LSOF_PROTOCOL_SCA,        /**< SCA(0x6007) */
    LSOF_PROTOCOL_TEB,        /**< TEB(0x6558) */
    LSOF_PROTOCOL_RARP,       /**< RARP(0x8035) */
    LSOF_PROTOCOL_ATALK,      /**< ATALK(0x809B) */
    LSOF_PROTOCOL_AARP,       /**< AARP(0x80F3) */
    LSOF_PROTOCOL_8021Q,      /**< 8021Q(0x8100) */
    LSOF_PROTOCOL_IPX,        /**< IPX(0x8137) */
    LSOF_PROTOCOL_PAUSE,      /**< PAUSE(0x8808) */
    LSOF_PROTOCOL_SLOW,       /**< SLOW(0x8809) */
    LSOF_PROTOCOL_WCCP,       /**< WCCP(0x883E) */
    LSOF_PROTOCOL_MPLS_UC,    /**< MPLS_UC(0x8847) */
    LSOF_PROTOCOL_MPLS_MC,    /**< MPLS_MC(0x8848) */
    LSOF_PROTOCOL_ATMMPOA,    /**< ATMMPOA(0x884C) */
    LSOF_PROTOCOL_PPP_DISC,   /**< PPP_DISC(0x8863) */
    LSOF_PROTOCOL_PPP_SES,    /**< PPP_SES(0x8864) */
    LSOF_PROTOCOL_LINK_CTL,   /**< LINK_CTL(0x886C) */
    LSOF_PROTOCOL_ATMFATE,    /**< ATMFATE(0x8884) */
    LSOF_PROTOCOL_PAE,        /**< PAE(0x888E) */
    LSOF_PROTOCOL_PROFINET,   /**< PROFINET(0x8892) */
    LSOF_PROTOCOL_REALTEK,    /**< REALTEK(0x8899) */
    LSOF_PROTOCOL_AOE,        /**< AOE(0x88A2) */
    LSOF_PROTOCOL_ETHERCAT,   /**< ETHERCAT(0x88A4) */
    LSOF_PROTOCOL_8021AD,     /**< 8021AD(0x88A8) */
    LSOF_PROTOCOL_802_EX1,    /**< 802_EX1(0x88B5) */
    LSOF_PROTOCOL_ERSPAN,     /**< ERSPAN(0x88BE) */
    LSOF_PROTOCOL_PREAUTH,    /**< PREAUTH(0x88C7) */
    LSOF_PROTOCOL_TIPC,       /**< TIPC(0x88CA) */
    LSOF_PROTOCOL_LLDP,       /**< LLDP(0x88CC) */
    LSOF_PROTOCOL_MRP,        /**< MRP(0x88E3) */
    LSOF_PROTOCOL_MACSEC,     /**< MACSEC(0x88E5) */
    LSOF_PROTOCOL_8021AH,     /**< 8021AH(0x88E7) */
    LSOF_PROTOCOL_MVRP,       /**< MVRP(0x88F5) */
    LSOF_PROTOCOL_1588,       /**< 1588(0x88F7) */
    LSOF_PROTOCOL_NCSI,       /**< NCSI(0x88F8) */
    LSOF_PROTOCOL_PRP,        /**< PRP(0x88FB) */
    LSOF_PROTOCOL_CFM,        /**< CFM(0x8902) */
    LSOF_PROTOCOL_FCOE,       /**< FCOE(0x8906) */
    LSOF_PROTOCOL_TDLS,       /**< TDLS(0x890D) */
    LSOF_PROTOCOL_FIP,        /**< FIP(0x8914) */
    LSOF_PROTOCOL_IBOE,       /**< IBOE(0x8915) */
    LSOF_PROTOCOL_80221,      /**< 80221(0x8917) */
    LSOF_PROTOCOL_HSR,        /**< HSR(0x892F) */
    LSOF_PROTOCOL_NSH,        /**< NSH(0x894F) */
    LSOF_PROTOCOL_LOOPBACK,   /**< LOOPBACK(0x9000) */
    LSOF_PROTOCOL_QINQ1,      /**< QINQ1(0x9100) */
    LSOF_PROTOCOL_QINQ2,      /**< QINQ2(0x9200) */
    LSOF_PROTOCOL_QINQ3,      /**< QINQ3(0x9300) */
    LSOF_PROTOCOL_EDSA,       /**< EDSA(0xDADA) */
    LSOF_PROTOCOL_DSA_8021Q,  /**< DSA_8021Q(0xDADB) */
    LSOF_PROTOCOL_DSA_A5PSW,  /**< DSA_A5PSW(0xE001) */
    LSOF_PROTOCOL_IFE,        /**< IFE(0xED3E) */
    LSOF_PROTOCOL_AF_IUCV,    /**< AF_IUCV(0xFBFB) */
};
