#!/bin/bash
#
# Mksrc - make Solaris source files
#
# WARNING: This script assumes it is running from the main directory
#	   of the lsof, version 4 distribution.
#
# One environment variable applies:
#
# LSOF_MKC	is the method for creating the source files.
#		It defaults to "ln -s".  A common alternative is "cp".
#
# $Id: Mksrc,v 1.4 2000/12/04 14:35:13 abe Exp $

mksrc() {
  for i in $L
  do
    rm -f $i
    $LSOF_MKC $D/$i $i
    echo "$LSOF_MKC $D/$i $i"
  done
}

D=lib/dialects/sun
L="ddev.c dfile.c dlsof.h dmnt.c dnode.c dnode1.c dnode2.c dproc.c dproto.h dsock.c dstore.c machine.h"

mksrc
