#!/bin/bash
#
# Mksrc - make Linux source files for /proc-based lsof
#
# WARNING: This script assumes it is running from the main directory
#	   of the lsof, version 4 distribution.
#
# One environment variable applies:
#
# LSOF_MKC	is the method for creating the source files.
#		It defaults to "ln -s".  A common alternative is "cp".
#
# $Id: Mksrc,v 1.2 2000/12/04 14:31:02 abe Exp $

mksrc() {
  for i in $L
  do
    rm -f $i
    $LSOF_MKC $D/$i $i
    echo "$LSOF_MKC $D/$i $i"
  done
}

D=lib/dialects/linux
L="dfile.c dlsof.h dmnt.c dnode.c dproc.c dproto.h dsock.c dstore.c machine.h"

mksrc

D=src
L="arg.c main.c print.c ptti.c store.c usage.c util.c"

mksrc

D=src/dialects/linux
L="dprint.c"

mksrc
